# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token a1a8f2fb57f460f2f86464732597db976df30fab

{
  "title": "Шкаф",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/6/
Content-Type: application/json
Authorization: Token fa903ec2b71b41a41c9067254c2c691750f92058

{
  "status": "OPEN"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=4
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2023-01-30
Content-Type: application/json

###

# фильтрация по дате
DELETE  {{baseUrl}}/advertisements/6/
Content-Type: application/json
Authorization: Token fa903ec2b71b41a41c9067254c2c691750f92058