# Generated by Django 4.1.5 on 2023-01-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='image',
            field=models.ImageField(max_length=60, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(default=None, max_length=60),
        ),
    ]
